name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-angular:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      working-directory: ./LocalFoodFrontend

    - name: Build Angular application
      run:  ng build --configuration=development
      working-directory: ./LocalFoodFrontend

    - name: Run Angular tests
      run: ng test --code-coverage --watch=false --browsers=ChromeHeadless
      working-directory: ./LocalFoodFrontend

  build-and-test-go:
    runs-on: ubuntu-latest
    needs: build-and-test-angular

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.1'

    - name: Build Go application
      run: go build 
      working-directory: ./LocalFoodBackend

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install docker-compose -y

    - name: Build and run Docker Compose
      run: docker-compose up -d
      working-directory: ./LocalFoodBackend/Docker

    - name: Run Go tests
      run: go test
      working-directory: ./LocalFoodBackend/Tests
